### ISSUE TITLE
auto release action

### ISSUE THREAD

**Issue by nanozuki** [nanozuki/dantalian#12]
Add action to auto-release dantalian. 
Once tagged commit, add release includes Linux, BSD, and OSX versions, and publish to crates.io.

**Comment by laxect** [comment]
Auto build release may not work because of hyper use Openssl.

**Comment by nanozuki** [comment]
@laxect because of C lib? We can ingore Windows platform

**Comment by laxect** [comment]
> @laxect because of C lib? We can ignore Windows platform

Because of Openssl. Will need musl.

**Comment by laxect** [comment]
Basically, complete on #21.
