### ISSUE TITLE
Fail to run on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by acc557** [nanozuki/dantalian#20]
``/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found``

**Comment by acc557** [comment]
@laxect  `GLIBC_2.32` seems to be too new for most of the distributions. 
Is there any workaround for Ubuntu users?

**Comment by laxect** [comment]
You can build yourself for now. We will update the build action soon.

**Comment by laxect** [comment]
should work now
